### PR TITLE
167 fix parseurl query

### LINKED ISSUE #167: NavBar#parseUrlAndReplaceQuery seems a bit broken
Take [this route](https://graphhopper.com/maps2/?point=52.610119%2C13.319295&point=52.560485%2C13.233999&point=52.50787%2C13.256825&point=52.477149%2C13.380564&point=52.524685%2C13.459852&point=52.601365%2C13.391376&point=52.565597%2C13.349329&profile=car&layer=OpenStreetMap) for example. Move a marker and then click the back button. Multiple `/route` requests are fired and we can also notice that the camera is moving in a weird way and there are rapid updates of the heightgraph (both because of the many route requests).

I noticed this when I was trying to find a solution for #162. Let's take a look at the code:

https://github.com/graphhopper/graphhopper-maps/blob/fbe18e16a4ab0b3e3d9451246acf3ab13a832528/src/NavBar.ts#L89-L113

This code runs when we hit the 'back' button of the browser, because we add an event listener for the `popstate` event in the `NavBar` constructor. At first sight `this.isIgnoreQueryStoreUpdates = true` looks like we can manipulate the state without triggering any routing requests. But this flag only blocks the code that is run in `onQueryStateChanged`, which updates the url. The standard receivers of the query state change are still registered and will fire the routing requests. Because the request was valid before, it will remain valid when we remove each of the points and there will be a routing request after every point we remove. Similarly, there will be even more routing requests when add points in the next line, and even another one when we set the profile.

`parseUrlAndReplaceQuery` is not only called when the `popstate` event occurs, but also when the app loads for the first time (see `index.tsx`). In this case only one route request is fired, but this is rather coincidental it seems. When we refresh the page the `QueryStore` will be in it's initial state, namely with two (empty) points and an **empty** profile name:

https://github.com/graphhopper/graphhopper-maps/blob/fbe18e16a4ab0b3e3d9451246acf3ab13a832528/src/stores/QueryStore.ts#L69-L84

This means the query store state is invalid initially and this check in `routeIfAllPointsSet`:

https://github.com/graphhopper/graphhopper-maps/blob/fbe18e16a4ab0b3e3d9451246acf3ab13a832528/src/stores/QueryStore.ts#L200-L204

will be false so no request will be fired. When we then remove the (empty) points in `parseUrlAndReplaceQuery` the request will still be invalid. It will be invalid even after we add the points from the url, because the profile will be missing still. Only when we set the profile at the end of `parseUrlAndReplaceQuery` the request finally becomes valid and a request will be fired. Therefore these single `AddPoint/RemovePoint` actions seem a bit odd to me. Since we know the query store state that we would like to set after we parsed the url would it not be a lot more intuitive to simply update the store's state **once** using all the information we got?

This is closely related to #162, because for #162 we also need to tweak the app's behavior following the url parsing and the initial `/info` and `/route` requests.

Here is a (preliminary) todo list:

* [ ] only trigger one route request when the `popstate` event occurs
* [ ] maybe just update the query store state once instead of dispatching multiple `Add/RemovePoint` events.

### PR DESCRIPTION
**Pull request by Janekdererste**
* Add action which sets all routing params at once
* Change navbar so that it sets the query points and the routing profile at once
* make the query store digest the setrutingparamsatonce action

fixes #167

### CODE REVIEW

**Comment by Janekdererste** [comment]
Hups, just noticing that I gave the wrong ticket number in the branch 😅

File: src/stores/QueryStore.ts [hunk 1]
```diff
@@ -84,14 +85,7 @@ export default class QueryStore extends Store<QueryStoreState> {
     }
 
     reduce(state: QueryStoreState, action: Action): QueryStoreState {
-        if (action instanceof SetPoint) {
-            const newState: QueryStoreState = {
-                ...state,
-                queryPoints: QueryStore.replacePoint(state.queryPoints, action.point),
```
Comment (easbar) [inline src/stores/QueryStore.ts:90]: Very minor, but it looks like you changed the order of the if/else blocks for `SetPoint` and `InvalidatePoint` here for no real reason? Without this change it would be a bit easier to see what changed in this PR.

**Review by easbar — APPROVED** [review]
Thanks! I tested this PR and I can confirm that the rapid route updates after clicking the back button I described in #167 are fixed.

File: src/NavBar.ts [hunk 2]
```diff
@@ -95,26 +95,28 @@ export default class NavBar {
...
-        // assuming that at least two points should be present add un-initialized points if necessary
-        for (let i = this.queryStore.state.queryPoints.length; i < 2; i++) {
-            Dispatcher.dispatch(new AddPoint(i, { lat: 0, lng: 0 }, false))
-        }
-
-        // add routing profile
-        Dispatcher.dispatch(new SetVehicleProfile(parseResult.profile))
+        // we want either all the points replaced from the url or we just have one and we want to replace the one default
+        // one
+        const points = parseResult.points.length > 2 ? parseResult.points : this.fillPoints(parseResult.points)
```
Comment (easbar) [inline src/NavBar.ts:100]: When do we have only a single point and with which default one do we want to replace this?

**Review by easbar — APPROVED** [review]

File: src/NavBar.ts (hunk 2 above)
Comment (Janekdererste) [reply src/NavBar.ts:100]: This is the case, when the url contains only 1 point. Since we don't have information about the index of this point, this assumes that this single point is the starting point.

File: src/stores/QueryStore.ts (hunk 1 above)
Comment (Janekdererste) [reply src/stores/QueryStore.ts:90]: You are right. I changed the order so that ```SetPoint```, ```AddPoint```, ```SetParametersAtOnce``` are close to each other. I can put this back however.

File: src/NavBar.ts (hunk 2 above)
Comment (easbar) [reply src/NavBar.ts:100]: Ah ok if I enter only one point in the url the first input field is populated and the second remains empty. So this seems to work :)

File: src/stores/QueryStore.ts (hunk 1 above)
Comment (easbar) [reply src/stores/QueryStore.ts:90]: No no that makes sense then!

File: src/NavBar.ts (hunk 2 above)
Comment (Janekdererste) [reply src/NavBar.ts:100]: Yes, that's what I meant :-)
